documented_pos = [
    ['NEG', 'YES', 'NEG', 'Tebelopele', 'NO'],
    ['NEG', 'YES', 'NEG', 'Lab result form', 'NO'],
    ['NEG', 'YES', 'NEG', 'PMTCT Prescription', 'NO'],
    ['NEG', 'YES', 'NEG', 'Record of CD4 count', 'NO'],
    ['NEG', 'YES', 'NEG', 'OTHER', 'NO'],
    ['NEG', 'YES', 'UNKNOWN', 'Tebelopele', 'NO'],
    ['NEG', 'YES', 'UNKNOWN', 'Lab result form', 'NO'],
    ['NEG', 'YES', 'UNKNOWN', 'PMTCT Prescription', 'NO'],
    ['NEG', 'YES', 'UNKNOWN', 'Record of CD4 count', 'NO'],
    ['NEG', 'YES', 'UNKNOWN', 'OTHER', 'NO'],
    ['NEG', 'YES', 'IND', 'Tebelopele', 'NO'],
    ['NEG', 'YES', 'IND', 'Lab result form', 'NO'],
    ['NEG', 'YES', 'IND', 'PMTCT Prescription', 'NO'],
    ['NEG', 'YES', 'IND', 'Record of CD4 count', 'NO'],
    ['NEG', 'YES', 'IND', 'OTHER', 'NO'],
    ['NEG', 'YES', None, 'Tebelopele', 'NO'],
    ['NEG', 'YES', None, 'Lab result form', 'NO'],
    ['NEG', 'YES', None, 'PMTCT Prescription', 'NO'],
    ['NEG', 'YES', None, 'Record of CD4 count', 'NO'],
    ['NEG', 'YES', None, 'OTHER', 'NO'],
    ['NEG', 'NO', 'POS', 'Tebelopele', 'NO'],
    ['NEG', 'NO', 'POS', 'Lab result form', 'NO'],
    ['NEG', 'NO', 'POS', 'PMTCT Prescription', 'NO'],
    ['NEG', 'NO', 'POS', 'Record of CD4 count', 'NO'],
    ['NEG', 'NO', 'POS', 'OTHER', 'NO'],
    ['NEG', 'NO', 'NEG', 'Tebelopele', 'NO'],
    ['NEG', 'NO', 'NEG', 'Lab result form', 'NO'],
    ['NEG', 'NO', 'NEG', 'PMTCT Prescription', 'NO'],
    ['NEG', 'NO', 'NEG', 'Record of CD4 count', 'NO'],
    ['NEG', 'NO', 'NEG', 'OTHER', 'NO'],
    ['NEG', 'NO', 'UNKNOWN', 'Tebelopele', 'NO'],
    ['NEG', 'NO', 'UNKNOWN', 'Lab result form', 'NO'],
    ['NEG', 'NO', 'UNKNOWN', 'PMTCT Prescription', 'NO'],
    ['NEG', 'NO', 'UNKNOWN', 'Record of CD4 count', 'NO'],
    ['NEG', 'NO', 'UNKNOWN', 'OTHER', 'NO'],
    ['NEG', 'NO', 'IND', 'Tebelopele', 'NO'],
    ['NEG', 'NO', 'IND', 'Lab result form', 'NO'],
    ['NEG', 'NO', 'IND', 'PMTCT Prescription', 'NO'],
    ['NEG', 'NO', 'IND', 'Record of CD4 count', 'NO'],
    ['NEG', 'NO', 'IND', 'OTHER', 'NO'],
    ['NEG', 'NO', None, 'Tebelopele', 'NO'],
    ['NEG', 'NO', None, 'Lab result form', 'NO'],
    ['NEG', 'NO', None, 'PMTCT Prescription', 'NO'],
    ['NEG', 'NO', None, 'Record of CD4 count', 'NO'],
    ['NEG', 'NO', None, 'OTHER', 'NO'],
    ['NEG', 'N/A', 'POS', 'Tebelopele', 'NO'],
    ['NEG', 'N/A', 'POS', 'Lab result form', 'NO'],
    ['NEG', 'N/A', 'POS', 'PMTCT Prescription', 'NO'],
    ['NEG', 'N/A', 'POS', 'Record of CD4 count', 'NO'],
    ['NEG', 'N/A', 'POS', 'OTHER', 'NO'],
    ['NEG', 'N/A', 'NEG', 'Tebelopele', 'NO'],
    ['NEG', 'N/A', 'NEG', 'Lab result form', 'NO'],
    ['NEG', 'N/A', 'NEG', 'PMTCT Prescription', 'NO'],
    ['NEG', 'N/A', 'NEG', 'Record of CD4 count', 'NO'],
    ['NEG', 'N/A', 'NEG', 'OTHER', 'NO'],
    ['NEG', 'N/A', 'UNKNOWN', 'Tebelopele', 'NO'],
    ['NEG', 'N/A', 'UNKNOWN', 'Lab result form', 'NO'],
    ['NEG', 'N/A', 'UNKNOWN', 'PMTCT Prescription', 'NO'],
    ['NEG', 'N/A', 'UNKNOWN', 'Record of CD4 count', 'NO'],
    ['NEG', 'N/A', 'UNKNOWN', 'OTHER', 'NO'],
    ['NEG', 'N/A', 'IND', 'Tebelopele', 'NO'],
    ['NEG', 'N/A', 'IND', 'Lab result form', 'NO'],
    ['NEG', 'N/A', 'IND', 'PMTCT Prescription', 'NO'],
    ['NEG', 'N/A', 'IND', 'Record of CD4 count', 'NO'],
    ['NEG', 'N/A', 'IND', 'OTHER', 'NO'],
    ['NEG', 'N/A', None, 'Tebelopele', 'NO'],
    ['NEG', 'N/A', None, 'Lab result form', 'NO'],
    ['NEG', 'N/A', None, 'PMTCT Prescription', 'NO'],
    ['NEG', 'N/A', None, 'Record of CD4 count', 'NO'],
    ['NEG', 'N/A', None, 'OTHER', 'NO'],
]

differences = [
    ['NEG', 'YES', 'NEG', 'Tebelopele', 'NO'],
    ['NEG', 'YES', 'NEG', 'Lab result form', 'NO'],
    ['NEG', 'YES', 'NEG', 'ART Prescription', 'NO'],
    ['NEG', 'YES', 'NEG', 'PMTCT Prescription', 'NO'],
    ['NEG', 'YES', 'NEG', 'Record of CD4 count', 'NO'],
    ['NEG', 'YES', 'NEG', 'OTHER', 'NO'],
    ['NEG', 'YES', 'UNKNOWN', 'Tebelopele', 'NO'],
    ['NEG', 'YES', 'UNKNOWN', 'Lab result form', 'NO'],
    ['NEG', 'YES', 'UNKNOWN', 'ART Prescription', 'NO'],
    ['NEG', 'YES', 'UNKNOWN', 'PMTCT Prescription', 'NO'],
    ['NEG', 'YES', 'UNKNOWN', 'Record of CD4 count', 'NO'],
    ['NEG', 'YES', 'UNKNOWN', 'OTHER', 'NO'],
    ['NEG', 'YES', 'IND', 'Tebelopele', 'NO'],
    ['NEG', 'YES', 'IND', 'Lab result form', 'NO'],
    ['NEG', 'YES', 'IND', 'ART Prescription', 'NO'],
    ['NEG', 'YES', 'IND', 'PMTCT Prescription', 'NO'],
    ['NEG', 'YES', 'IND', 'Record of CD4 count', 'NO'],
    ['NEG', 'YES', 'IND', 'OTHER', 'NO'],
    ['NEG', 'YES', None, 'Tebelopele', 'NO'],
    ['NEG', 'YES', None, 'Lab result form', 'NO'],
    ['NEG', 'YES', None, 'ART Prescription', 'NO'],
    ['NEG', 'YES', None, 'PMTCT Prescription', 'NO'],
    ['NEG', 'YES', None, 'Record of CD4 count', 'NO'],
    ['NEG', 'YES', None, 'OTHER', 'NO'],
    ['NEG', 'NO', 'POS', 'Tebelopele', 'NO'],
    ['NEG', 'NO', 'POS', 'Lab result form', 'NO'],
    ['NEG', 'NO', 'POS', 'ART Prescription', 'NO'],
    ['NEG', 'NO', 'POS', 'PMTCT Prescription', 'NO'],
    ['NEG', 'NO', 'POS', 'Record of CD4 count', 'NO'],
    ['NEG', 'NO', 'POS', 'OTHER', 'NO'],
    ['NEG', 'NO', 'NEG', 'Tebelopele', 'NO'],
    ['NEG', 'NO', 'NEG', 'Lab result form', 'NO'],
    ['NEG', 'NO', 'NEG', 'ART Prescription', 'NO'],
    ['NEG', 'NO', 'NEG', 'PMTCT Prescription', 'NO'],
    ['NEG', 'NO', 'NEG', 'Record of CD4 count', 'NO'],
    ['NEG', 'NO', 'NEG', 'OTHER', 'NO'],
    ['NEG', 'NO', 'UNKNOWN', 'Tebelopele', 'NO'],
    ['NEG', 'NO', 'UNKNOWN', 'Lab result form', 'NO'],
    ['NEG', 'NO', 'UNKNOWN', 'ART Prescription', 'NO'],
    ['NEG', 'NO', 'UNKNOWN', 'PMTCT Prescription', 'NO'],
    ['NEG', 'NO', 'UNKNOWN', 'Record of CD4 count', 'NO'],
    ['NEG', 'NO', 'UNKNOWN', 'OTHER', 'NO'],
    ['NEG', 'NO', 'IND', 'Tebelopele', 'NO'],
    ['NEG', 'NO', 'IND', 'Lab result form', 'NO'],
    ['NEG', 'NO', 'IND', 'ART Prescription', 'NO'],
    ['NEG', 'NO', 'IND', 'PMTCT Prescription', 'NO'],
    ['NEG', 'NO', 'IND', 'Record of CD4 count', 'NO'],
    ['NEG', 'NO', 'IND', 'OTHER', 'NO'],
    ['NEG', 'NO', None, 'Tebelopele', 'NO'],
    ['NEG', 'NO', None, 'Lab result form', 'NO'],
    ['NEG', 'NO', None, 'ART Prescription', 'NO'],
    ['NEG', 'NO', None, 'PMTCT Prescription', 'NO'],
    ['NEG', 'NO', None, 'Record of CD4 count', 'NO'],
    ['NEG', 'NO', None, 'OTHER', 'NO'],
    ['NEG', 'N/A', 'POS', 'Tebelopele', 'NO'],
    ['NEG', 'N/A', 'POS', 'Lab result form', 'NO'],
    ['NEG', 'N/A', 'POS', 'ART Prescription', 'NO'],
    ['NEG', 'N/A', 'POS', 'PMTCT Prescription', 'NO'],
    ['NEG', 'N/A', 'POS', 'Record of CD4 count', 'NO'],
    ['NEG', 'N/A', 'POS', 'OTHER', 'NO'],
    ['NEG', 'N/A', 'NEG', 'Tebelopele', 'NO'],
    ['NEG', 'N/A', 'NEG', 'Lab result form', 'NO'],
    ['NEG', 'N/A', 'NEG', 'ART Prescription', 'NO'],
    ['NEG', 'N/A', 'NEG', 'PMTCT Prescription', 'NO'],
    ['NEG', 'N/A', 'NEG', 'Record of CD4 count', 'NO'],
    ['NEG', 'N/A', 'NEG', 'OTHER', 'NO'],
    ['NEG', 'N/A', 'UNKNOWN', 'Tebelopele', 'NO'],
    ['NEG', 'N/A', 'UNKNOWN', 'Lab result form', 'NO'],
    ['NEG', 'N/A', 'UNKNOWN', 'ART Prescription', 'NO'],
    ['NEG', 'N/A', 'UNKNOWN', 'PMTCT Prescription', 'NO'],
    ['NEG', 'N/A', 'UNKNOWN', 'Record of CD4 count', 'NO'],
    ['NEG', 'N/A', 'UNKNOWN', 'OTHER', 'NO'],
    ['NEG', 'N/A', 'IND', 'Tebelopele', 'NO'],
    ['NEG', 'N/A', 'IND', 'Lab result form', 'NO'],
    ['NEG', 'N/A', 'IND', 'ART Prescription', 'NO'],
    ['NEG', 'N/A', 'IND', 'PMTCT Prescription', 'NO'],
    ['NEG', 'N/A', 'IND', 'Record of CD4 count', 'NO'],
    ['NEG', 'N/A', 'IND', 'OTHER', 'NO'],
    ['NEG', 'N/A', None, 'Tebelopele', 'NO'],
    ['NEG', 'N/A', None, 'Lab result form', 'NO'],
    ['NEG', 'N/A', None, 'ART Prescription', 'NO'],
    ['NEG', 'N/A', None, 'PMTCT Prescription', 'NO'],
    ['NEG', 'N/A', None, 'Record of CD4 count', 'NO'],
    ['NEG', 'N/A', None, 'OTHER', 'NO'],
    ['UNKNOWN', 'YES', 'NEG', 'ART Prescription', 'NO'],
    ['UNKNOWN', 'YES', 'UNKNOWN', 'ART Prescription', 'NO'],
    ['UNKNOWN', 'YES', 'IND', 'ART Prescription', 'NO'],
    ['UNKNOWN', 'YES', None, 'ART Prescription', 'NO'],
    ['UNKNOWN', 'NO', 'POS', 'ART Prescription', 'NO'],
    ['UNKNOWN', 'NO', 'NEG', 'ART Prescription', 'NO'],
    ['UNKNOWN', 'NO', 'UNKNOWN', 'ART Prescription', 'NO'],
    ['UNKNOWN', 'NO', 'IND', 'ART Prescription', 'NO'],
    ['UNKNOWN', 'NO', None, 'ART Prescription', 'NO'],
    ['UNKNOWN', 'N/A', 'POS', 'ART Prescription', 'NO'],
    ['UNKNOWN', 'N/A', 'NEG', 'ART Prescription', 'NO'],
    ['UNKNOWN', 'N/A', 'UNKNOWN', 'ART Prescription', 'NO'],
    ['UNKNOWN', 'N/A', 'IND', 'ART Prescription', 'NO'],
    ['UNKNOWN', 'N/A', None, 'ART Prescription', 'NO'],
    ['IND', 'YES', 'NEG', 'ART Prescription', 'NO'],
    ['IND', 'YES', 'UNKNOWN', 'ART Prescription', 'NO'],
    ['IND', 'YES', 'IND', 'ART Prescription', 'NO'],
    ['IND', 'YES', None, 'ART Prescription', 'NO'],
    ['IND', 'NO', 'POS', 'ART Prescription', 'NO'],
    ['IND', 'NO', 'NEG', 'ART Prescription', 'NO'],
    ['IND', 'NO', 'UNKNOWN', 'ART Prescription', 'NO'],
    ['IND', 'NO', 'IND', 'ART Prescription', 'NO'],
    ['IND', 'NO', None, 'ART Prescription', 'NO'],
    ['IND', 'N/A', 'POS', 'ART Prescription', 'NO'],
    ['IND', 'N/A', 'NEG', 'ART Prescription', 'NO'],
    ['IND', 'N/A', 'UNKNOWN', 'ART Prescription', 'NO'],
    ['IND', 'N/A', 'IND', 'ART Prescription', 'NO'],
    ['IND', 'N/A', None, 'ART Prescription', 'NO'],
]
